services:
- type: web
  name: rabbitmq
  env: docker
  envVars:
  - key: RABBITMQ_ERLANG_COOKIE
    generateValue: true
  - key: RABBITMQ_DEFAULT_USER
    value: rabbitmq
  - key: RABBITMQ_DEFAULT_PASS
    generateValue: true
  - key: RABBITMQ_MNESIA_BASE
    value: /var/lib/rabbitmq/mnesia
  - key: RABBITMQ_MNESIA_DIR
    value: /var/lib/rabbitmq/mnesia/data
  disk:
    name: rabbitmq
    mountPath: /var/lib/rabbitmq
    sizeGB: 10
