services:
- type: web
  name: rabbitmq
  env: docker
  envVars:
  - key: RABBITMQ_ERLANG_COOKIE
    generateValue: true
  - key: RABBITMQ_DEFAULT_USER
    value: rabbitmq
  - key: RABBITMQ_DEFAULT_PASS
    generateValue: true
  - key: RABBITMQ_NODENAME
    fromService:
      type: web
      name: rabbitmq # same as the name defined above so it can refer to itself
      property: host
  disk:
    name: rabbitmq
    mountPath: /var/lib/rabbitmq
    sizeGB: 10

